### ISSUE TITLE
Add GitHub Action to automatically add companies from Issue Templates

### ISSUE THREAD

**Issue by j0hnm4r5** [j0hnm4r5/awesome-creative-technology#62]

**Comment by j0hnm4r5** [comment]
50ee9fb12b75e245ba72bf2d0e465d9f66fbae87 adds an issue template

**Comment by JohnENoonan** [comment]
Hey @j0hnm4r5, I just added this functionality on [my fork](https://github.com/JohnENoonan/awesome-creative-technology). You can create an issue and if it has the label `new addition` then an action is triggered which will add the information from the created issue and make a pull request which you can merge in to include the new studio. I recommend turning on "Automatically delete head branches" so that the branch gets deleted when merged in. Let me know if you'd like to include this and I can make a pull request. Thanks as always!

**Comment by j0hnm4r5** [comment]
Yeah that’s amazing. PR the heck outta that and I’ll merge it right in.

**Comment by JohnENoonan** [comment]
I updated my PR #69. It's pretty messy because of deleting all the node_modules files, I promise I didn't actually update 5000 files 😄
